#! /usr/bin/env bash

# bootstrap
source scripts/bootstrap.sh

# environments
export PATH="$BTF_HOME/utilities/leiningen:$PATH"
export LEIN_HOME="$BTF_HOME/utilities/leiningen"

# auto provisioning
scripts/upgrade.rb config/provision.yaml
