base:
    - python: "2.7.3"
    - ruby: "1.9.3"
    - java: "openjdk-7-jdk"
    - node: "0.10.13"
    - lua: "5.1"

utilities:
    - leiningen: "2.2.0"

packages:
    - leiningen: "2.2.0"

services:
    - nginx: "1.4.2"
    - redis: "2.6.14"
    - elasticsearch: "0.90.2"
